# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/forklift.konveyor.io_forkliftcontrollers.yaml
- bases/forklift.konveyor.io_hooks.yaml
- bases/forklift.konveyor.io_hosts.yaml
- bases/forklift.konveyor.io_migrations.yaml
- bases/forklift.konveyor.io_networkmaps.yaml
- bases/forklift.konveyor.io_plans.yaml
- bases/forklift.konveyor.io_providers.yaml
- bases/forklift.konveyor.io_storagemaps.yaml
- bases/forklift.konveyor.io_ovirtvolumepopulators.yaml
- bases/forklift.konveyor.io_openstackvolumepopulators.yaml
- bases/forklift.konveyor.io_vspherexcopyvolumepopulators.yaml
#+kubebuilder:scaffold:crdkustomizeresource
