## test values
### cluster config
test-namespace: vsphere-populator-test-2
kubeconfig: #####
secret-name: populator-secret
pvc-yaml-path: assets/manifests/xcopy-setup/xcopy-pvc.yaml
test-labels: vsphere-populator
### images
test-image-label:  latest
test-populator-image: quay.io/kubev2v/vsphere-copy-offload-populator
### storage
storage-password-file: #### # Path to file containing storage password
storage-user: #######
storage-url: #######
storage-class-name: ########
storage-skip-ssl-verification: "true"

### vsphere
vsphere-password-file: ######### # Path to file containing vSphere password
vsphere-user: ########
vsphere-url: #########
vsphere-datastore: ##########
vsphere-resource-pool: Resources

### VM config (New section for VM parameters)
iso-path: #######
data-center: #####
wait-timeout: 10m # e.g., "10m", "1h", "30s"
download-vmdk-url: "" # Leave empty for default, or provide a URL
local-vmdk-path: ##### route to a vmdk to be used as base