resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml

# Add MyCustomObject service account
- forklift-controller_service_account.yaml
- forklift-controller_role.yaml
- forklift-controller_role_binding.yaml
- forklift-controller_migrator_role.yml

# forklift-api service account
- api/service_account.yaml
- api/role.yaml
- api/role_binding.yaml

# forklift-populator-controller service account
- populator-controller/service_account.yaml
- populator-controller/role.yaml
- populator-controller/role_binding.yaml

# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
# - authproxy/service.yaml
# - authproxy/role.yaml
# - authproxy/role_binding.yaml
# - authproxy/client_clusterrole.yaml
