---
apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: ${NAMESPACE}
spec:
  feature_ui_plugin: "true"
  feature_validation: "true"
  feature_volume_populator: "true"
  # Enable NetworkPolicies. Set to "true" to install policies.
  # When enabled, a baseline defaultâ€‘deny (Ingress+Egress) policy is applied and
  # Forklift policies explicitly allow required traffic.
  feature_network_policies: "false"

